version: '3.2'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nodejs_test
      MYSQL_USER: nodejs_test
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQLX: 'OFF'
    command: --pid-file=/run/mysqld/mysqld.pid
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - '8080:80'
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: nodejs_test
      DB_FLAVOUR: mysql
      JWT_SECRET: 'QWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY3NzIz'

volumes:
  db_data:
  node_modules:
